### ISSUE TITLE
Git push fails with error

### ISSUE THREAD

**Issue by salvationarinze** [StephanWagner/bitbucket-git-ftp#1]
Hi, nice repo. I tried using it to create a bitbucket pipeline following the instructions you gave and it always filed with an error: git ftp init push -u $FTP_USERNAME -p $FTP_PASSWORD ftp://$FTP_HOST
fatal: Could not get last commit. Network down? Wrong URL? Use 'git ftp init' for the initial push., exiting...

Please help

**Comment by stephanwagner** [comment]
That could be two reasons.

- The Pipeline can’t connect to the FTP host. Remember, it is normal FTP,
not SFTP.

- Or as stated in the text, Git-ftp wasn’t initialized. You have to do that
manually. See section Initialize Git-ftp here: https://stephanwagner.me/deploy-websites-with-bitbucket-pipelines-and-git-ftp
